### ISSUE TITLE
Incorrect error information

### ISSUE THREAD

**Issue by hpav** [facade/flare-client-php#26]
Hello! When any error occurs, displays "assert" the error instead of the actual error information, every time (See screenshot).
The problem is on version 1.9.1, on version 1.8.1 everything is fine
![image](https://user-images.githubusercontent.com/30503521/145784144-755f9859-f6bb-4352-b73c-6d1952357a38.png)

**Comment by AlexVanderbist** [comment]
Hi @hpav, sorry for the late reply. This package was abandoned some time ago. Please switch to using https://github.com/spatie/ignition or https://github.com/spatie/flare-client-php. If you can't use these newer packages due to version constraints we'll happily merge any PR that fixes issues in this repo. Thanks!
